### ISSUE TITLE
cloudmusic-zd423: Download failed

### ISSUE THREAD

**Issue by manjaroyyq** [Ryanjiena/Tian#9]
### Package Name

cloudmusic-zd423

### Terminal Output

```powershell
$ scoop install cloudmusic-zd423
安装 'cloudmusic-zd423' (2.9.9.199909) [64bit]
远程服务器返回错误: (500) 内部服务器错误。
地址 https://pan.jiemi.workers.dev/?file=/zd423/CloudMusic_v2.9.9.199909.7z 无效
```

**Comment by JaimeZeng** [comment]
> ### Package Name
> cloudmusic-zd423
> 
> ### Terminal Output
> ```powershell
> $ scoop install cloudmusic-zd423
> 安装 'cloudmusic-zd423' (2.9.9.199909) [64bit]
> 远程服务器返回错误: (500) 内部服务器错误。
> 地址 https://pan.jiemi.workers.dev/?file=/zd423/CloudMusic_v2.9.9.199909.7z 无效
> ```

Done.

**Comment by JaimeZeng** [comment]
等三个小后后仓库自动同步
